// Code generated by goctl. DO NOT EDIT.
// Modified to use GORM instead of sqlx
// goctl version: 1.9.2

package model

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (int64, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByEmail(ctx context.Context, email string) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
		List(ctx context.Context, offset, limit int64) ([]*User, int64, error)
	}

	defaultUserModel struct {
		db *gorm.DB
	}

	User struct {
		ID        int64     `gorm:"column:id;primaryKey;autoIncrement" json:"id"`
		Name      string    `gorm:"column:name;type:varchar(255);not null" json:"name"`
		Email     string    `gorm:"column:email;type:varchar(255);uniqueIndex;not null" json:"email"`
		Age       int64     `gorm:"column:age;type:integer;default:0" json:"age"`
		CreatedAt time.Time `gorm:"column:created_at;autoCreateTime" json:"created_at"`
		UpdatedAt time.Time `gorm:"column:updated_at;autoUpdateTime" json:"updated_at"`
	}
)

// TableName 指定表名
func (User) TableName() string {
	return "user"
}

func newUserModel(db *gorm.DB) *defaultUserModel {
	return &defaultUserModel{
		db: db,
	}
}

// Delete 删除用户
func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {
	result := m.db.WithContext(ctx).Delete(&User{}, id)
	return result.Error
}

// FindOne 根据 ID 查询用户
func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	var user User
	result := m.db.WithContext(ctx).First(&user, id)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		return nil, result.Error
	}
	return &user, nil
}

// FindOneByEmail 根据邮箱查询用户
func (m *defaultUserModel) FindOneByEmail(ctx context.Context, email string) (*User, error) {
	var user User
	result := m.db.WithContext(ctx).Where("email = ?", email).First(&user)
	if result.Error != nil {
		if errors.Is(result.Error, gorm.ErrRecordNotFound) {
			return nil, ErrNotFound
		}
		return nil, result.Error
	}
	return &user, nil
}

// Insert 插入用户
func (m *defaultUserModel) Insert(ctx context.Context, data *User) (int64, error) {
	result := m.db.WithContext(ctx).Create(data)
	if result.Error != nil {
		return 0, result.Error
	}
	return data.ID, nil
}

// Update 更新用户
func (m *defaultUserModel) Update(ctx context.Context, data *User) error {
	result := m.db.WithContext(ctx).Save(data)
	return result.Error
}

// List 分页查询用户列表
func (m *defaultUserModel) List(ctx context.Context, offset, limit int64) ([]*User, int64, error) {
	var users []*User

	// 查询列表
	result := m.db.WithContext(ctx).Limit(int(limit)).Offset(int(offset)).Find(&users)
	if result.Error != nil {
		return nil, 0, result.Error
	}

	// 查询总数
	var total int64
	countResult := m.db.WithContext(ctx).Model(&User{}).Count(&total)
	if countResult.Error != nil {
		return nil, 0, countResult.Error
	}

	return users, total, nil
}
