// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type DeleteUserReq struct {
	Id int64 `path:"id"` // 从 URL 路径获取用户 ID
}

type DeleteUserResp struct {
	Message string `json:"message"` // 操作结果消息
}

type GetUserReq struct {
	Id int64 `path:"id"` // 从 URL 路径获取 id
}

type GetUserResp struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

type ListUsersReq struct {
	Page     int64 `form:"page,default=1"`       // 页码，默认第1页
	PageSize int64 `form:"page_size,default=10"` // 每页数量，默认10条
}

type ListUsersResp struct {
	List     []UserItem `json:"list"`      // 用户列表
	Total    int64      `json:"total"`     // 总数
	Page     int64      `json:"page"`      // 当前页
	PageSize int64      `json:"page_size"` // 每页数量
}

type RegisterReq struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type RegisterResp struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UpdateUserReq struct {
	Id    int64  `path:"id"`    // 从 URL 路径获取用户 ID
	Name  string `json:"name"`  // 新的用户名
	Email string `json:"email"` // 新的邮箱
}

type UpdateUserResp struct {
	Message string `json:"message"` // 操作结果消息
}

type User struct {
	Id         int64  `json:"id"`
	Name       string `json:"name"`
	Email      string `json:"email"`
	CreateTime string `json:"create_time"`
}

type UserItem struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
